
###############################################################################
#
# Inclusive Makefile for the arm64_mlnx_msn2700 module.
#
# Autogenerated 2015-12-23 23:45:22.262891
#
###############################################################################
arm64_mlnx_msn2700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

