
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-mlnx-msn2700 module.
#
# Autogenerated 2016-10-13 22:58:39.095824
#
###############################################################################
libonlp-arm64-mlnx-msn2700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

