
###############################################################################
#
# Inclusive Makefile for the arm64mlnx_msn2700 module.
#
# Autogenerated 2015-12-23 23:45:56.754200
#
###############################################################################
arm64mlnx_msn2700_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(arm64mlnx_msn2700_BASEDIR)/module/make.mk
include $(arm64mlnx_msn2700_BASEDIR)/module/auto/make.mk
include $(arm64mlnx_msn2700_BASEDIR)/module/src/make.mk

